#!/bin/bash
set -a

# GCP vars
GOOGLE_APPLICATION_CREDENTIALS_FOLDER="${HOME}/.google/credentials/"
GOOGLE_APPLICATION_CREDENTIALS_FILE="earthquake-usgs-8ad22dd8ee91.json"
GCP_PROJECT_ID=earthquake-usgs
GCP_PROJECT_REGION=europe-west2
GCP_PROJECT_DATA_LAKE_NAME=earthquake-usgs_data
GCP_PROJECT_BQ_DATASET_NAME=earthquake_usgs

# 
# DO NOT edit the following
# 
AIRFLOW_UID=$(id -u)
GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS_FOLDER}${GOOGLE_APPLICATION_CREDENTIALS_FILE}
TF_VAR_PROJECT=${GCP_PROJECT_ID}
TF_VAR_REGION=${GCP_PROJECT_REGION}
TF_VAR_DATA_LAKE_BUCKET=${GCP_PROJECT_DATA_LAKE_NAME}
TF_VAR_BQ_DATASET=${GCP_PROJECT_BQ_DATASET_NAME}
set +a
